### ISSUE TITLE
Types: Failing tests for Oracle timestamps w/ time zone against Snowflake precision=3

### ISSUE THREAD

**Issue by sirupsen** [datafold/data-diff#136] opened 2022-06-30 16:30 UTC
@erezsh I've uncovered a new set of incompatibility bugs. Unfortunately it doesn't show up in CI because it doesn't do Oracle yet.

On branch `test-snowflake-prod` these tests fail with round errors:

* `test_types_oracle_ts6_y_tz_snowflake_ts3_50`
* `test_types_oracle_ts9_y_tz_snowflake_ts3_50`
* `test_types_oracle_ts_y_tz_snowflake_ts3_50`

Run with `poetry run python -m unittest -k test_types_oracle_ts_y_tz_snowflake_ts3_50` with that branch checked out.

Sample error:

```
======================================================================
test_types_oracle_ts_y_tz_snowflake_ts3_50 (tests.test_database_types.TestDiffCrossDatabaseTables)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/data-diff-yPhKwkIo-py3.10/lib/python3.10/site-packages/parameterized/parameterized.py", line 533, in standalo
ne_func
    return func(*(a + p.args), **p.kwargs)
  File "/root/data-diff/tests/test_database_types.py", line 611, in test_types
    self.assertEqual(expected, diff)
AssertionError: Lists differ: [] != [('-', ('6', '2022-06-01 15:10:05.010000')[2287 chars]0'))]

Second list contains 52 additional elements.
First extra element 0:
('-', ('6', '2022-06-01 15:10:05.010000'))

- []
+ [('-', ('6', '2022-06-01 15:10:05.010000')),
+  ('+', ('6', '2022-06-01 15:10:05.009000')),
+  ('-', ('7', '2000-01-01 00:00:03.001000')),
+  ('+', ('7', '2000-01-01 00:00:03.000000')),
+  ('-', ('9', '2000-01-01 00:00:09.002000')),
+  ('+', ('9', '2000-01-01 00:00:09.001000')),
+  ('-', ('11', '2000-01-01 00:00:15.003000')),
+  ('+', ('11', '2000-01-01 00:00:15.002000')),
+  ('-', ('13', '2000-01-01 00:00:21.004000')),
+  ('+', ('13', '2000-01-01 00:00:21.003000')),
+  ('-', ('14', '2000-01-01 00:00:24.005000')),
```

**Comment by erezsh** [comment] 2022-07-28 11:09
Duplicate of #123 (fixed)

**Closed by erezsh** 2022-07-28 11:09 UTC
Labels: bug
